import { createContext, useCallback, useContext, useEffect, useRef, useState, type ReactNode } from 'react';
import { AlertTriangle, X } from 'lucide-react';
type ConfirmOptions = { title: string; message: string; confirmText?: string; cancelText?: string; danger?: boolean };
type Pending = ConfirmOptions & { resolve: (value: boolean) => void };
const DialogContext = createContext<{ confirm: (options: ConfirmOptions) => Promise<boolean> }>({ confirm: async () => false });
export function DialogProvider({ children }: { children: ReactNode }) {
  const [pending, setPending] = useState<Pending | null>(null); const lastFocus = useRef<HTMLElement | null>(null);
  const confirm = useCallback((options: ConfirmOptions) => new Promise<boolean>(resolve => { lastFocus.current = document.activeElement as HTMLElement; setPending({ ...options, resolve }); }), []);
  const close = useCallback((value: boolean) => { if (!pending) return; pending.resolve(value); setPending(null); requestAnimationFrame(() => lastFocus.current?.focus()); }, [pending]);
  useEffect(() => { if (!pending) return; const onKey = (e: KeyboardEvent) => { if (e.key === 'Escape') close(false); }; document.addEventListener('keydown', onKey); document.body.style.overflow = 'hidden'; return () => { document.removeEventListener('keydown', onKey); document.body.style.overflow = ''; }; }, [pending, close]);
  return <DialogContext.Provider value={{ confirm }}>{children}{pending && <div className="fixed inset-0 z-[200] flex items-center justify-center bg-black/55 p-4" role="presentation" onMouseDown={e => { if (e.target === e.currentTarget) close(false); }}><section role="dialog" aria-modal="true" aria-labelledby="tf-confirm-title" className="w-full max-w-md rounded-xl border p-5 shadow-2xl" style={{ background: 'var(--color-surface)', borderColor: 'var(--color-border-strong)' }}><div className="flex items-start gap-3"><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full" style={{ background: pending.danger ? 'rgba(255,76,41,.16)' : 'var(--color-accent-soft)', color: pending.danger ? 'var(--color-error)' : 'var(--color-accent)' }}><AlertTriangle size={18} /></div><div className="min-w-0 flex-1"><h2 id="tf-confirm-title" className="text-base font-semibold" style={{ color: 'var(--color-text-primary)' }}>{pending.title}</h2><p className="mt-2 text-sm leading-relaxed" style={{ color: 'var(--color-text-secondary)' }}>{pending.message}</p></div><button onClick={() => close(false)} aria-label="Close dialog" className="p-1" style={{ color: 'var(--color-text-muted)' }}><X size={16} /></button></div><div className="mt-5 flex justify-end gap-2"><button onClick={() => close(false)} className="btn-secondary">{pending.cancelText || 'Cancel'}</button><button autoFocus onClick={() => close(true)} className="btn-primary">{pending.confirmText || 'Confirm'}</button></div></section></div>}</DialogContext.Provider>;
}
export const useDialog = () => useContext(DialogContext);
